version: '3.9'

services:
  mongodb:
    image: mongo:4.4.18
    container_name: mongodb
    networks:
      - server-network
    volumes:
      - ./:/usr/src/server
      - ./volumes/mongo:/data/db
    ports:
      - 27017:27017
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo localhost:27017/test --quiet
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  app:
    build:
      context: .
      dockerfile: ./build/Dockerfile
    ports:
      - 3000:3000
      - 5173:5173
    links:
      - mongodb
    depends_on:
      - mongodb
    networks:
      - server-network
    volumes:
      - ./:/usr/src/client
      - /usr/src/app/node_modules
networks:
  server-network: {}
